<?php
if(!defined('IN_PKW')) exit('Access Denied');
switch($skillext){
	case 101://='敌方二体降低攻击力';
break;
	case 102://='对手混乱';
break;
	case 103://='对手损失20体力';
break;
	case 104://='对手一定回合数内不能使用最后使用的技巧';
break;
	case 105://='提升自身特殊攻击力';
break;
	case 106://='己方受到攻击则提升威力';
break;
	case 107://='复制成为对方最后使用的技巧';
break;
	case 108://='对手降低两级防御力';
break;
	case 109://='提升自身回避率';
break;
	case 110://='自身回复1/2最大体力';
break;
	case 111://='自身变小且提升回避率';
break;
	case 112://='提升防御力,使用滚动和冰球威力加倍';
break;
	case 113://='己方会心一击几率的等级上升2级';
break;
	case 114://='己方略过行动阶段,2-3回合后将其间所受攻击伤害加倍反馈给当前敌场上对手';
break;
	case 115://='随机使用游戏中的技巧';
break;
	case 116://='己方丧失战斗力对场上全体精灵造成巨大伤害,计算伤害时对方防御减半';
break;
	case 117://='蓄力且暂时提升己方防御力,次回合攻击';
break;
	case 118://='复制对方的能力,技巧,属性';
break;
	case 119://='无效果';
break;
	case 120://='己方丧失战斗力对场上全体精灵造成巨大伤害';
break;
	case 121://='10%敌畏缩';
break;
	case 122://='自己属性随机转换为自己所拥有技巧属性中的一种';
break;
	case 123://='对手20%陷入冰冻/麻痹/烧伤状态随机一种';
break;
	case 124://='对手丧失当前1/2体力,小数点后无条件舍去';
break;
	case 125://='用自身1/4体力制造替身';
break;
	case 126://='没有PP时自动使用,自身体力失去最大值的1/4,可击中鬼系PM';
break;
	case 127://='忘记此技巧并永久学会对手使用的最后一个技巧';
	if($obv_skill['id']){
		$rev['skilllist'][] = $obv_skill['id'];
		$rev['skilllist'] = array_diff($rev['skilllist'], array($rev_skill['id']));
		$rev['skill'] = implode(',', $rev['skilllist']);
	}
break;
	case 128://='己方下回合必定命中';
break;
	case 129://='睡眠状态才能使用,30%敌畏缩';
break;
	case 130://='己方体力越少则威力越大';
break;
	case 131://='自己属性随机变为能抵抗对手上次攻击的属性之一';
break;
	case 132://='当回合防御对手攻击,连续使用成功率降低';
break;
	case 133://='对手降低两级速度';
break;
	case 134://='花费一半体力将攻击力提升至最高等级';
break;
	case 135://='对手回避率复原且普通和格斗系攻击技巧能攻击鬼系';
break;
	case 136://='全场精灵3回合后失去战斗力';
break;
	case 137://='先制,己方被一击消灭则残留1体力,连续使用成功率降低';
break;
	case 138://='对手降低两级攻击力';
break;
	case 139://='能够一击消灭对方时改为对方残留1体力';
break;
	case 140://='对手攻击力升两级且混乱';
break;
	case 141://='对手不可交换或逃跑';
break;
	case 142://='异性对手陷入媚惑状态,每回合50%不能行动';
break;
	case 143://='睡眠状态才能使用,随机抽取使用其它技巧,不会抽到需多个回合使用的技巧';
break;
	case 144://='己方全队异常状态恢复';
break;
	case 145://='亲密度越高威力越大';
break;
	case 146://='可能造成不同伤害或回复敌方一定体力';
break;
	case 147://='亲密度越低威力越大';
break;
	case 148://='5回合内己方全队不会被对手陷入异常状态,交换有效';
break;
	case 149://='与对手平分双方体力的总和';
break;
	case 150://='己方交换精灵且保持能力等级与某些状态';
break;
default:break;
}
?>