<?php
if(!defined('IN_PKW')) exit('Access Denied');
switch($skillext){
	case 251://='先制蓄力后制攻击,其间本体受到攻击则行动被打消';
break;
	case 252://='命中后己方降低攻击力和防御力';
break;
	case 253://='优先打破对手场上的反射盾与光壁,再攻击';
break;
	case 254://='能击中飞空中的PM';
break;
	case 255://='己方单体提升攻击力与防御力';
break;
	case 256://='对手睡眠则伤害加倍且解除睡眠';
break;
	case 257://='己方降低速度';
break;
	case 258://='己方降低防御和特殊防御力';
break;
	case 259://='非鬼系使用时降低速度提升攻击力与防御力,鬼系使用时自身损失一半体力及对方进入诅咒状态,每回合损失1/4体力';
break;
	case 260:if(rand(1, 10) <= 3) $obv['status'] = 3;break;
	case 261:$obv['status'] = 3;break;
	case 262:$obv['status'] = 3;$obv['hp'] -= ($obv['maxhp'] / 16);break;
	case 263:if(rand(1, 5) <= 2) $obv['status'] = 3;break;
	case 264:if(rand(1, 10) <= 3){$obv['status'] = 3;$obv['hp']-= ($obv['maxhp'] / 16);}break;
	case 265:$vitalrand = 5;if(rand(1, 10) == 1) $obv['status'] = 3;break;
	case 266://='对手特性无效';
break;
	case 267://='最多使用2次,撒1次对方交换时中毒,2次中剧毒,飞行系和飘浮特性PM不受影响,非飞行系或飘浮特性的毒系PM上场时能清除毒菱';
break;
	case 268:$vitalrand = 5;if(rand(1, 10) == 1) $obv['status'] = 3;break;
	case 269:$obvhurt*= 2;if(rand(1, 5) == 1) $obv['status'] = 3;break;
	case 270://='敌方二体降低速度';
break;
	case 271://='连续使用每命中一次威力加倍,首次威力10,未命中则中止攻击';
break;
	case 272://='造成伤害后己方交换精灵';
break;
	case 273://='对方的果实效果转移至自身并使用掉果实';
break;
	case 274://='攻击空中敌人伤害加倍';
break;
	case 275://='蓄力时飞在天空,次回合进行攻击';
break;
	case 276://='复制使用对方技巧';
break;
	case 277://='当回合蓄力,次回合攻击,30%敌害怕';
break;
	case 278://='蓄力时跃到高空,次回合攻击,30%敌麻痹';
break;
	case 279://='回复1/2最大体力且此回合暂时失去飞行属性的抗性';
break;
	case 280://='我方一定回合内全体速度提升两级';
break;
	case 281://='对手回避率下降,清除对方反射盾/光壁/神秘护身的效果';
break;
	case 282://='录音攻击,随录音音量大小,不同几率地追加混乱（最高100%）';
break;
default:break;
}
?>