<?php
if(!defined('IN_PKW')) exit('Access Denied');
switch($skillext){
	case 151://='对手一定回合数内只能使用最后使用的技巧';
break;
	case 152://='清除己方场地的撒菱/毒菱/秘密岩石/寄生种子/暂时性束缚技巧的效果';
break;
	case 153://='敌方二体降低回避率';
break;
	case 154://='回复1/2最大体力,晴天回复量2/3,雨天/沙尘暴/冰雹回复量1/4';
break;
	case 155://='威力与属性随个体值而变化';
	if(!isset($rev['iv_hp'])){
		$revext = $db->fetch_first("SELECT iv_hp,iv_atk,iv_def,iv_stk,iv_sdf,iv_spd FROM {$PKWpre}mymonext WHERE id=$rev[id]");
		$rev = array_merge($rev, $revext);
	}
	$rev_skill['power'] = hidden_power($rev);
	$rev_skill['atb'] = hidden_type($rev);
break;
	case 156://='复制对方的能力等级';
break;
	case 157://='先制攻击且敌100%畏缩,只能在首回合使用';
break;
	case 158://='连续攻击2-5回合,自身不会陷入睡眠状态,已睡觉PM醒来';
break;
	case 159://='蓄力且暂时提升防御与特殊防御力';
break;
	case 160://='威力随蓄力次数改变';
break;
	case 161://='回复体力量随蓄力次数而改变';
break;
	case 162://='己方中毒,麻痹,烧伤时威力加倍';
break;
	case 163://='对手麻痹则伤害加倍且解除麻痹';
break;
	case 164://='所有单体攻击转移目标至自身';
break;
	case 165://='随战斗环境改变为不同技巧';
break;
	case 166://='先制,本回合队友的伤害增加50%';
break;
	case 167://='下回合己方场上精灵回复1/2最大体力';
break;
	case 168://='随机使用队友的技能';
break;
	case 169://='己方已使用的道具复原';
break;
	case 170://='对手下回合睡眠';
break;
	case 171://='伤害量等同于对方体力高于我方体力的数量且不可为负数';
break;
	case 172://='自身解除麻痹/烧伤/中毒状态';
break;
	case 173://='30%的附加效果随战斗场地而改变';
break;
	case 174://='随战斗场地转换自身属性';
break;
	case 175://='除自身外全体混乱';
break;
	case 176://='对手50%防御力下降';
break;
	case 177://='属性随天气改变,有天气时威力加倍';
break;
	case 178://='对手回避率复原且普通和格斗系攻击技巧能攻击鬼系,鬼系攻击技巧能攻击普通系';
break;
	case 179://='对手降低攻击力与防御力';
break;
	case 180://='自己身上未携带道具则得到对手道具并装备于自身';
break;
	case 181://='威力和属性随携带果实不同而变化';
break;
	case 182://='只有对方使用保护或见切时才造成伤害';
break;
	case 183://='自身随机一项能力提升两级,双打时可任选场上目标';
break;
	case 184://='此招PP越少威力越大';
break;
	case 185://='对手体力越少威力越大';
break;
	case 186://='一定回合内己方全队不会被会心一击';
break;
	case 187://='若对方攻击己方且己方先攻则使出对手的招，并且威力1.5倍补正 若对方攻击且己方先攻则使出对手的招';
break;
	case 188://='变为上次使用的技巧';
break;
	case 189://='其它技巧均使用过方可使用此技巧,若是此招是唯一技巧则无法使用';
break;
	case 190://='敌二体异性对手特殊攻击力降两级';
break;
	case 191://='属性随所带薄板变化';
break;
	case 192://='一回合内做出两次连续攻击';
break;
	case 193://='对手交换精灵则先攻且伤害加倍';
break;
	case 194://='对手20%防御力下降';
break;
	case 195://='全队未陷入异常状态者均做出一次此攻击,无视属性,计算伤害时用种族值代替攻防实际能力';
break;
	case 196://='对手不可连续使用同一技巧,对已开始的多回合连续攻击技(滚动/冰球/暴走/花瓣舞/逆鳞/吵闹)无效';
break;
	case 197://='对手特殊攻击力升1级且混乱';
break;
	case 198://='己方丧失战斗力,对手攻击与特殊攻击力降两级';
break;
	case 199://='对手2-4回合不可使用非攻击技巧';
break;
	case 200://='对手道具暂时消失,对战后恢复';
break;
default:break;
}
?>